### ISSUE TITLE
Task Edit - Assignees ajaxChosen

### ISSUE THREAD

**Issue by angek** [angek/ProjectSpoon#45]
project_id is not being passed correctly when trying to assign assignees to a task therefore assignee list, in some instances, incorrectly reports that no matched are found.

**Comment by angek** [comment]
resolved with commit bc66fe5

**Comment by enbzz** [comment]
in the installed versions of the packages from the projectspoon website this  issue is still present. maybe we need a new release not yet available?
